config/routes.rb
Rails.application.routes.draw do
  get 'finish/:id' => 'components#finish'
  get 'engine_games/:id' => 'games#engine_games'
  resources :resource_tags
  resources :resource_comments
  resources :resource_ratings
  resources :resources
  resources :component_comments
  resources :asset_ratings
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'engines#index'

  resources :users
  resources :tags
  resources :asset_tags
  resources :component_tags
  resources :game_tags
  resources :engine_tags
  resources :asset_comments
  resources :game_comments
  resources :game_comments
  resources :engine_comments
  resources :component_ratings
  resources :game_ratings
  resources :engine_ratings
  resources :component_in_games
  resources :licenses
  resources :categories
  resources :credits
  resources :incentives
  resources :assets
  resources :components
  resources :games
  resources :engines

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.user? 
      can :manage, [Engine]
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :asset_comments
  has_many :asset_ratings
  has_many :asset_tags
  has_many :incentives
  has_many :credits
  belongs_to :component
  belongs_to :category
  belongs_to :license
end

app/models/asset_rating.rb
class AssetRating < ActiveRecord::Base
end

app/models/asset_tag.rb
class AssetTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :engine
  has_many :games, through: :component_in_games
  has_many :component_in_games
  belongs_to :license
  has_many :component_ratings
  has_many :resources
  has_many :component_tags
  mount_uploader :image, FileUploader
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :user
  belongs_to :resource
end

app/models/engine.rb
class Engine < ActiveRecord::Base
  has_many :engine_comments
  has_many :engine_ratings
  has_many :engine_tags
  has_many :components
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/engine_tag.rb
class EngineTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :engine
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_comments
  has_many :game_ratings
  has_many :game_tags
  has_many :components, through: :component_in_games
  has_many :component_in_games
  belongs_to :engine
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/game_rating.rb
class GameRating < ActiveRecord::Base
end

app/models/game_tag.rb
class GameTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/incentive.rb
class Incentive < ActiveRecord::Base
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :license
  belongs_to :category
  has_many :resource_ratings
  mount_uploader :image, FileUploader
  mount_uploader :download, FileUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :engine_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  delegate :can?, :cannot?, :to => :ability
  #before_validation :make_first_user_admin!
  has_many :credits

  def set_default_role
    if User.count == 0
       self.admin = true
    else
       self.user = true
    end
  end
   
  def make_first_user_admin!
    if User.count == 0
       self.admin = true
    end
  end
  
  def ability
    @ability ||= Ability.new(self)
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.user = true
      end
  end
  
end

app/controllers/asset_ratings_controller.rb
class AssetRatingsController < ApplicationController
  before_action :set_asset_rating, only: [:show, :edit, :update, :destroy]

  # GET /asset_ratings
  # GET /asset_ratings.json
  def index
    @asset_ratings = AssetRating.all
  end

  # GET /asset_ratings/1
  # GET /asset_ratings/1.json
  def show
  end

  # GET /asset_ratings/new
  def new
    @asset_rating = AssetRating.new
  end

  # GET /asset_ratings/1/edit
  def edit
  end

  # POST /asset_ratings
  # POST /asset_ratings.json
  def create
    @asset_rating = AssetRating.new(asset_rating_params)

    respond_to do |format|
      if @asset_rating.save
        format.html { redirect_to @asset_rating, notice: 'Asset rating was successfully created.' }
        format.json { render :show, status: :created, location: @asset_rating }
      else
        format.html { render :new }
        format.json { render json: @asset_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asset_ratings/1
  # PATCH/PUT /asset_ratings/1.json
  def update
    respond_to do |format|
      if @asset_rating.update(asset_rating_params)
        format.html { redirect_to @asset_rating, notice: 'Asset rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset_rating }
      else
        format.html { render :edit }
        format.json { render json: @asset_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_ratings/1
  # DELETE /asset_ratings/1.json
  def destroy
    @asset_rating.destroy
    respond_to do |format|
      format.html { redirect_to asset_ratings_url, notice: 'Asset rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset_rating
      @asset_rating = AssetRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_rating_params
      params.require(:asset_rating).permit(:asset_id, :rating)
    end
end

app/helpers/asset_ratings_helper.rb
module AssetRatingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/asset_ratings/_form.html.erb
<%= form_for(@asset_rating) do |f| %>
  <% if @asset_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset_rating.errors.count, "error") %> prohibited this asset_rating from being saved:</h2>

      <ul>
      <% @asset_rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asset_id %><br>
    <%= f.number_field :asset_id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asset_ratings/edit.html.erb
<h1>Editing Asset Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset_rating %> |
<%= link_to 'Back', asset_ratings_path %>

app/views/asset_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Asset Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Asset</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asset_ratings.each do |asset_rating| %>
      <tr>
        <td><%= asset_rating.asset_id %></td>
        <td><%= asset_rating.rating %></td>
        <td><%= link_to 'Show', asset_rating %></td>
        <td><%= link_to 'Edit', edit_asset_rating_path(asset_rating) %></td>
        <td><%= link_to 'Destroy', asset_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset rating', new_asset_rating_path %>

app/views/asset_ratings/new.html.erb
<h1>New Asset Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', asset_ratings_path %>

app/views/asset_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asset:</strong>
  <%= @asset_rating.asset_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @asset_rating.rating %>
</p>

<%= link_to 'Edit', edit_asset_rating_path(@asset_rating) %> |
<%= link_to 'Back', asset_ratings_path %>