config/routes.rb
Rails.application.routes.draw do
  get 'finish/:id' => 'components#finish'
  get 'engine_games/:id' => 'games#engine_games'
  resources :resource_tags
  resources :resource_comments
  resources :resource_ratings
  resources :resources
  resources :component_comments
  resources :asset_ratings
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'engines#index'

  resources :users
  resources :tags
  resources :asset_tags
  resources :component_tags
  resources :game_tags
  resources :engine_tags
  resources :asset_comments
  resources :game_comments
  resources :game_comments
  resources :engine_comments
  resources :component_ratings
  resources :game_ratings
  resources :engine_ratings
  resources :component_in_games
  resources :licenses
  resources :categories
  resources :credits
  resources :incentives
  resources :assets
  resources :components
  resources :games
  resources :engines

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.user? 
      can :manage, [Engine]
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :asset_comments
  has_many :asset_ratings
  has_many :asset_tags
  has_many :incentives
  has_many :credits
  belongs_to :component
  belongs_to :category
  belongs_to :license
end

app/models/asset_rating.rb
class AssetRating < ActiveRecord::Base
end

app/models/asset_tag.rb
class AssetTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :engine
  has_many :games, through: :component_in_games
  has_many :component_in_games
  belongs_to :license
  has_many :component_ratings
  has_many :resources
  has_many :component_tags
  mount_uploader :image, FileUploader
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :user
  belongs_to :resource
end

app/models/engine.rb
class Engine < ActiveRecord::Base
  has_many :engine_comments
  has_many :engine_ratings
  has_many :engine_tags
  has_many :components
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/engine_tag.rb
class EngineTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :engine
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_comments
  has_many :game_ratings
  has_many :game_tags
  has_many :components, through: :component_in_games
  has_many :component_in_games
  belongs_to :engine
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/game_rating.rb
class GameRating < ActiveRecord::Base
end

app/models/game_tag.rb
class GameTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/incentive.rb
class Incentive < ActiveRecord::Base
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :license
  belongs_to :category
  has_many :resource_ratings
  mount_uploader :image, FileUploader
  mount_uploader :download, FileUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :engine_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  delegate :can?, :cannot?, :to => :ability
  #before_validation :make_first_user_admin!
  has_many :credits

  def set_default_role
    if User.count == 0
       self.admin = true
    else
       self.user = true
    end
  end
   
  def make_first_user_admin!
    if User.count == 0
       self.admin = true
    end
  end
  
  def ability
    @ability ||= Ability.new(self)
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.user = true
      end
  end
  
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:user_id, :asset_id)
    end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :asset_id %><br>
    <%= f.number_field :asset_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credits</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Asset</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.user_id %></td>
        <td><%= credit.asset_id %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @credit.user_id %>
</p>

<p>
  <strong>Asset:</strong>
  <%= @credit.asset_id %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>