config/routes.rb
Rails.application.routes.draw do
  get 'finish/:id' => 'components#finish'
  get 'engine_games/:id' => 'games#engine_games'
  resources :resource_tags
  resources :resource_comments
  resources :resource_ratings
  resources :resources
  resources :component_comments
  resources :asset_ratings
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'engines#index'

  resources :users
  resources :tags
  resources :asset_tags
  resources :component_tags
  resources :game_tags
  resources :engine_tags
  resources :asset_comments
  resources :game_comments
  resources :game_comments
  resources :engine_comments
  resources :component_ratings
  resources :game_ratings
  resources :engine_ratings
  resources :component_in_games
  resources :licenses
  resources :categories
  resources :credits
  resources :incentives
  resources :assets
  resources :components
  resources :games
  resources :engines

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.user? 
      can :manage, [Engine]
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :asset_comments
  has_many :asset_ratings
  has_many :asset_tags
  has_many :incentives
  has_many :credits
  belongs_to :component
  belongs_to :category
  belongs_to :license
end

app/models/asset_tag.rb
class AssetTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :engine
  has_many :games, through: :component_in_games
  has_many :component_in_games
  belongs_to :license
  has_many :component_ratings
  has_many :resources
  has_many :component_tags
  mount_uploader :image, FileUploader
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :user
  belongs_to :resource
end

app/models/engine.rb
class Engine < ActiveRecord::Base
  has_many :engine_comments
  has_many :engine_ratings
  has_many :engine_tags
  has_many :components
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/engine_tag.rb
class EngineTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :engine
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_comments
  has_many :game_ratings
  has_many :game_tags
  has_many :components, through: :component_in_games
  has_many :component_in_games
  belongs_to :engine
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/game_rating.rb
class GameRating < ActiveRecord::Base
end

app/models/game_tag.rb
class GameTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/incentive.rb
class Incentive < ActiveRecord::Base
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :license
  belongs_to :category
  has_many :resource_ratings
  mount_uploader :image, FileUploader
  mount_uploader :download, FileUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :engine_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  delegate :can?, :cannot?, :to => :ability
  #before_validation :make_first_user_admin!
  has_many :credits

  def set_default_role
    if User.count == 0
       self.admin = true
    else
       self.user = true
    end
  end
   
  def make_first_user_admin!
    if User.count == 0
       self.admin = true
    end
  end
  
  def ability
    @ability ||= Ability.new(self)
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.user = true
      end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :name %></label>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %><br>
    </div>
  </div>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :image %></label>
    <div class="col-sm-10">
      <%= f.file_field :image %><br>
    </div>
  </div>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :component_id %></label>
    <div class="col-sm-10">
      <%= f.number_field :component_id, :class => "form-control" %><br>
    </div>
  </div>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :category_id %></label>
    <div class="col-sm-10">
      <%= f.number_field :category_id, :class => "form-control" %><br>
    </div>
  </div>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :download %></label>
    <div class="col-sm-10">
      <%= f.file_field :download %><br>
    </div>
  </div>

  <div class="field">
    <label class="col-sm-2 col-sm-2 control-label"><%= f.label :license_id %></label>
    <div class="col-sm-10">
      <%= f.text_field :license_id, :class => "form-control" %><br>
    </div>
  </div>

  <div class="field">
   <label class="col-sm-2 col-sm-2 control-label"> <%= f.label :video %></label>
   <div class="col-sm-10">
      <%= f.text_field :video, :class => "form-control" %><br>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
    <button  class = "btn btn-theme"><%= link_to 'Back', :back %></button>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Component</th>
      <th>Category</th>
      <th>Download</th>
      <th>License</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.image %></td>
        <td><%= resource.component_id %></td>
        <td><%= resource.category_id %></td>
        <td><%= resource.download %></td>
        <td><%= resource.license_id %></td>
        <td><%= resource.video %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<section class="wrapper site-min-height">
	<div class="col-lg-6">
		<h1>New Resource</h1><br>

		<%= render 'form' %>
	</div>
</section>

app/views/resources/show.html.erb
          <section class="wrapper site-min-height">
            <h3><i class="fa fa-angle-right"></i> Information</h3>
            <hr>
        <div class="row mt">
          <div class="col-lg-6 moreHeight">
            <div class="project-wrapper">
                        <div class="project">
                            <div class="photo-wrapper">
                                <div class="photo">
                                  <a class="fancybox" href="assets/img/portfolio/port04.jpg"><img class="img-responsive" src="../assets/img/portfolio/port04.jpg" alt=""></a>
                                </div>
                                <div class="overlay"></div>
                            </div>
                        </div>
                    </div>
          </div><!-- col-lg-4 -->
        <!-- Information Here -->
          <div class="col-lg-6 col-md-6 col-sm-12">
              <!-- Description Here -->
              <h1><%= @resource.name %></h1>
              <h3>Licencia: <%= @resource.license.name %></h3>
              <p style = "font-family: Arial; font-size: 20px"><%= @resource.category.name %></p><br>
              <div class="ec-stars-wrapper">
              <% suma = 0 %>
              <% contador = 0 %>
                <% @resource.resource_ratings.each do |rating| %>
                  <% suma+= rating.rating %>
                  <% contador+=1 %>
                <% end %>
                <% promedio = 0 %>
                <% if contador > 0 %>
                  <% promedio = suma / contador %>
                <% end %>
                <% contador = 0 %>
                <% promedio.times do%>
                  <% contador+=1 %>
                  <ay href="#" data-value=<% contador.to_s %> >&#9733;</ay>
                <% end %>
                <% resto = 5 - promedio %>
                <% resto.times do%>
                  <ab href="#" data-value="1">&#9733;</ab>
                <% end %>
              </div>
              <label><%=promedio %>/5</label><br>
              <label>general rating</label><br>
              <a href="<%=@resource.download%>"><button type="button" class="btn btn-primary">Download</button></a>
            </div>


        </div><!-- /row --><br>