config/routes.rb
Rails.application.routes.draw do
  get 'finish/:id' => 'components#finish'
  get 'engine_games/:id' => 'games#engine_games'
  resources :resource_tags
  resources :resource_comments
  resources :resource_ratings
  resources :resources
  resources :component_comments
  resources :asset_ratings
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'engines#index'

  resources :users
  resources :tags
  resources :asset_tags
  resources :component_tags
  resources :game_tags
  resources :engine_tags
  resources :asset_comments
  resources :game_comments
  resources :game_comments
  resources :engine_comments
  resources :component_ratings
  resources :game_ratings
  resources :engine_ratings
  resources :component_in_games
  resources :licenses
  resources :categories
  resources :credits
  resources :incentives
  resources :assets
  resources :components
  resources :games
  resources :engines

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.user? 
      can :manage, [Engine]
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :asset_comments
  has_many :asset_ratings
  has_many :asset_tags
  has_many :incentives
  has_many :credits
  belongs_to :component
  belongs_to :category
  belongs_to :license
end

app/models/asset_tag.rb
class AssetTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :engine
  has_many :games, through: :component_in_games
  has_many :component_in_games
  belongs_to :license
  has_many :component_ratings
  has_many :resources
  has_many :component_tags
  mount_uploader :image, FileUploader
end

app/models/component_comment.rb
class ComponentComment < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :user
  belongs_to :resource
end

app/models/engine.rb
class Engine < ActiveRecord::Base
  has_many :engine_comments
  has_many :engine_ratings
  has_many :engine_tags
  has_many :components
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/engine_tag.rb
class EngineTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :engine
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_comments
  has_many :game_ratings
  has_many :game_tags
  has_many :components, through: :component_in_games
  has_many :component_in_games
  belongs_to :engine
  belongs_to :license
  mount_uploader :image, FileUploader
end

app/models/game_rating.rb
class GameRating < ActiveRecord::Base
end

app/models/game_tag.rb
class GameTag < ActiveRecord::Base
  belongs_to :tag
end

app/models/incentive.rb
class Incentive < ActiveRecord::Base
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :license
  belongs_to :category
  has_many :resource_ratings
  mount_uploader :image, FileUploader
  mount_uploader :download, FileUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :engine_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  delegate :can?, :cannot?, :to => :ability
  #before_validation :make_first_user_admin!
  has_many :credits

  def set_default_role
    if User.count == 0
       self.admin = true
    else
       self.user = true
    end
  end
   
  def make_first_user_admin!
    if User.count == 0
       self.admin = true
    end
  end
  
  def ability
    @ability ||= Ability.new(self)
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.user = true
      end
  end
  
end

app/controllers/component_comments_controller.rb
class ComponentCommentsController < ApplicationController
  before_action :set_component_comment, only: [:show, :edit, :update, :destroy]

  # GET /component_comments
  # GET /component_comments.json
  def index
    @component_comments = ComponentComment.all
  end

  # GET /component_comments/1
  # GET /component_comments/1.json
  def show
  end

  # GET /component_comments/new
  def new
    @component_comment = ComponentComment.new
  end

  # GET /component_comments/1/edit
  def edit
  end

  # POST /component_comments
  # POST /component_comments.json
  def create
    @component_comment = ComponentComment.new(component_comment_params)

    respond_to do |format|
      if @component_comment.save
        format.html { redirect_to @component_comment, notice: 'Component comment was successfully created.' }
        format.json { render :show, status: :created, location: @component_comment }
      else
        format.html { render :new }
        format.json { render json: @component_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /component_comments/1
  # PATCH/PUT /component_comments/1.json
  def update
    respond_to do |format|
      if @component_comment.update(component_comment_params)
        format.html { redirect_to @component_comment, notice: 'Component comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @component_comment }
      else
        format.html { render :edit }
        format.json { render json: @component_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /component_comments/1
  # DELETE /component_comments/1.json
  def destroy
    @component_comment.destroy
    respond_to do |format|
      format.html { redirect_to component_comments_url, notice: 'Component comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component_comment
      @component_comment = ComponentComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_comment_params
      params.require(:component_comment).permit(:component_id, :user_id, :comment)
    end
end

app/helpers/component_comments_helper.rb
module ComponentCommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/component_comments/_form.html.erb
<%= form_for(@component_comment) do |f| %>
  <% if @component_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@component_comment.errors.count, "error") %> prohibited this component_comment from being saved:</h2>

      <ul>
      <% @component_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component_id %><br>
    <%= f.number_field :component_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/component_comments/edit.html.erb
<h1>Editing Component Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @component_comment %> |
<%= link_to 'Back', component_comments_path %>

app/views/component_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Component Comments</h1>

<table>
  <thead>
    <tr>
      <th>Component</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @component_comments.each do |component_comment| %>
      <tr>
        <td><%= component_comment.component_id %></td>
        <td><%= component_comment.user_id %></td>
        <td><%= component_comment.comment %></td>
        <td><%= link_to 'Show', component_comment %></td>
        <td><%= link_to 'Edit', edit_component_comment_path(component_comment) %></td>
        <td><%= link_to 'Destroy', component_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Component comment', new_component_comment_path %>

app/views/component_comments/new.html.erb
<h1>New Component Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', component_comments_path %>

app/views/component_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @component_comment.component_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @component_comment.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @component_comment.comment %>
</p>

<%= link_to 'Edit', edit_component_comment_path(@component_comment) %> |
<%= link_to 'Back', component_comments_path %>